export const prodConstants = {
  DATA_REQUEST: "DATA_REQUEST",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_FAILURE: "DATA_FAILURE",
  REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS",
};
export const singleProdConstants = {
  SINGLE_DATA_REQUEST: "SINGLE_DATA_REQUEST",
  SINGLE_DATA_SUCCESS: "SINGLE_DATA_SUCCESS",
  SINGLE_DATA_FAILURE: "SINGLE_DATA_FAILURE",
  REMOVE_SINGLE_DATA: "REMOVE_SINGLE_DATA",
};
