export const prodConstants = {
  DATA_REQUEST: "DATA_REQUEST",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_FAILURE: "DATA_FAILURE",
};
export const singleProdConstants = {
  SINGLE_DATA_REQUEST: "SINGLE_DATA_REQUEST",
  SINGLE_DATA_SUCCESS: "SINGLE_DATA_SUCCESS",
  SINGLE_DATA_FAILURE: "SINGLE_DATA_FAILURE",
};
